### ISSUE TITLE
can't find the header file library

### ISSUE THREAD

**Issue by Pratham24th** [gaborszita/adeept-spider-robot-improved#2]
please provide the following adeet header file directories. @gaborszita

**Comment by gaborszita** [comment]
@draxterrex 
I added a folder called AdeeptLibrary which contains these libraries in zip files. You need to add these in the Arduino IDE by going to Sketch -> Include Library ->Add ZIP Library... From there, you have to browse for the zip file and add it. You have to do this for all the library zip files (the AdeeptLibrary folder contains 3).

**Comment by Pratham24th** [comment]
you didn't  wrote the code for the controller?

**Comment by Pratham24th** [comment]
@gaborszita

**Comment by gaborszita** [comment]
@draxterrex 
I've added the remote control code in the Adeept6LegSpiderRobotMy4 folder called AdeeptRemoteControl.ino This is not my code, it's what the guys at Adeept wrote.

**Comment by Pratham24th** [comment]
can you provide the connection of arduino nano??
please :)

**Comment by gaborszita** [comment]
You mean how to upload the program on the arduino nano?

**Comment by Pratham24th** [comment]
Nooo, like how to connect the components for controller. *Actually I'm making my own controller.*

**Comment by gaborszita** [comment]
@draxterrex 
I'm not quite sure how to do that. I used the controller Adeept gave me with this kit. Here's a picture of it:
![image](https://user-images.githubusercontent.com/30361931/102865854-a7daf700-4436-11eb-942e-a1810b5b0fe6.png)
I would start with connecting the parts of the controller to the Arduino NANO based on this snippet of the controller code:
```
const int pot6Pin = 7;        // define R6
const int pot5Pin = 6;        // define R1
const int led1Pin = 6;        // define pin for LED1 which is close to NRF24L01 and used to indicate the state of NRF24L01 
const int led2Pin = 7;        // define pin for LED2 which is the mode is displayed in the Six foot robots remote control mode  
const int led3Pin = 8;        // define pin for LED3 which is the mode is displayed in the Six foot robots auto mode 
const int APin = 2;           // define pin for D2
const int BPin = 3;           // define pin for D3
const int CPin = 4;           // define pin for D4
const int DPin = 5;           // define pin for D5

const int u1XPin = 0;      // define pin for direction X of joystick U1
const int u1YPin = 1;      // define pin for direction Y of joystick U1
const int u2XPin = 2;      // define pin for direction X of joystick U2
const int u2YPin = 3;      // define pin for direction Y of joystick U2
```
But of course, if you wire it up differently, you can just change the code.
Good luck on making your own controller!

**Comment by gaborszita** [comment]
I'm closing this issue, because it went off-topic.

**Comment by Pratham24th** [comment]
okay thanks btw. :)
